# site settings

title: cv
description: Saria Said online CV
taglong: Saria Said online CV
tagshort: Saria Said
url: https://sariasaidcv.netlify.app
baseurl: ""
permalink: pretty
repo: https://github.com/appstartuparabic/appstartuparabic.github.io

# author settings

author:
  name: Saria Said
  email: appstartuparabic@gmail.com
photo: /assets/photo.png

# build settings

exclude:
  - LICENSE
  - README.md

sass:
  sass_dir: _sass
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
